/* Generated by Together */
package javaapplication37;

/**
 * For simplicity, dates are represented as simple integers, counting from 1 up to 365
@@ -20,15 +20,35 @@
 * Useful services offered by this class would probably be for checking if it's the first day of a new
 * academic year, and comparing dates within the year for equal, before and after.
 */

public class Date {
    /**

	 /**
     * For simplicity, dates will be represented just by an integer in the range 1-365. No Leap years!
     */
	private int dayNumber = 1;
        
        public int getDayNumber() 
        {
            return dayNumber;
        }

        public void setDayNumber(int dayNumber) 
        {
            this.dayNumber = dayNumber;
        }


	/**
     * This operation adds one to the day number, wrapping round to 1 after 365 automatically.
     */

    public void increment() {


    	if (getDayNumber() < 365) { 
    		setDayNumber(getDayNumber() + 1);
    	}
    	else {
    		setDayNumber(1);
    	}

    	// For testing output. System.out.println(dayNumber);
    }
}