//package javaapplication37;


import java.util.Hashtable;
//import javaapplication37.Date;
//import javaapplication37.Vehicle_info;

/* Generated by Together */

/**
 * For a description of Regular visitors, follow hyperlink to the Administration use case for
 * issuing a new Regular visitor permit.
 */
public class Regular_visitor_permit extends Permit {
    /**
     * The name of the University member hosting the visit.
     */
    private String hostName;

    /**
     * The date that the visit starts - entry will not be allowed before this date.
     * @label Starting on
     * @clientCardinality 1
     * @supplierCardinality 1
     * @link aggregation
     * @directed
     */
    private int lnkDate;
    private int permitType;

    /**
     * The date that the visit ends - entry will not be allowed after this date.
     * @label Ending on
     * @clientCardinality 1
     * @supplierCardinality 1
     * @link aggregation
     * @directed
     */
    private int lnkDate1;
    //Overloaded Constructor
    public Regular_visitor_permit(String  permitHolder, int permitType, String regNo, int noOfEntries, int warnings, boolean suspended, boolean enteredToday, Vehicle_info v1, Hashtable permittedVehicles, int lnkDate, int lnkDate1, String hostName)
    {
        super(permitHolder, permitType, regNo, noOfEntries, warnings, suspended, enteredToday, v1, permittedVehicles);
        this.lnkDate = lnkDate;
        this.lnkDate1 = lnkDate1;
        super.permitType = permitType;
        super.setHostName(hostName);
    }
}