
/* Generated by Together */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package javaapplication37;

import java.util.Hashtable;
import java.util.Iterator;
import java.util.Set;


/**
 * Each instance of Vehicle_info models an actual physical vehicle, so no two instances
 * may have the same registration number. There is no direct notation for this. Instead
 * the Vehicle list object collecting the Vehicles must enforce it by checking new additions
 * - the use of a HashTable in Vehicle_list with the registration number as key is helpful
 * with this.
 *
 * This class must contain at least the registration number, and may have any other attributes
 * that the University may from time to time find useful (such as car make, model, colour...).
 * @author bruce
 */
public class Vehicle_info {

	//Instance Variables for all the cars attributes
	private String regNo;
	private String make;
	private String model;
	private String colour;

	//Instance Variables for all the permit attributes
	private String permitId;
	private int warning;
	private int access;
	private Permit permit;
	private boolean suspended = false;

	//Instantiation of hashtable for vehicles and permitted vehicles
	private Hashtable vehicles;
	private Hashtable permitted;

	//constructor
	public Vehicle_info(String regNo)
	{
		this.regNo = regNo;
	}

	public Vehicle_info(String regNo, String make, String model, String colour, String permitId)
	{
		this.regNo = regNo;
		this.make = make;
		this.model = model;
		this.colour = colour;
		this.permitId = permitId;
		access = 0;
	}

	//Returns instance of Vehilce_info for the regNo entered today
	public Vehicle_info enteredToday(String regNo)
	{
		Vehicle_info today;
		today = (Vehicle_info) vehicles.get(regNo);
		return today;
	}

	/**
	 * Each vehicle (and so each registration number) is associated with exactly one permit,
	 * which describes its authorisation to enter the campus (or not!).
	 *
	 * This attribute references the permit associated with this vehicle. It allows the permit
	 * status of any vehicle to be accessed via the Vehicle_list knowing only the registration
	 * number - for example for barrier checks, recording warnings, and so on.
	 *
	 * Note that many vehicles may be associated with the same permit.
	 * @supplierCardinality 1
	 * @clientCardinality 1..*
	 * @label Allowed entry by
	 * @directed
    public Vehicle_info(String regNo){
        lnkPermit = new Permit();
        this.regNo = regNo;
        this.warning = false;
   }
	 */
	public boolean hasPermit()//Retuens true if permit is not null
	{   
		if (permit!=null) {
			return true;
		}else {
			return false;
		}
	}
	public Permit getPermit() {//Returns the permit
		return permit;
	}

	public void setPermit(Permit p)//Sets the permit
	{

		permit = p;

	}
	public void deletePermit()//Deletes ther permit
	{ 

		permit = null;
	}
	
    //Getters and Setters
	public String getReg()
	{   //returns reg
		return regNo;
	}
	public String getMake()
	{   //returns reg
		return make;
	}
	public void setMake(String m)
	{   //returns reg
		make = m;
	}
	public String getModel()
	{   //returns reg
		return model;
	}
	public void setModel(String m)
	{   //returns reg
		model=m;
	}
	public String getColour()
	{   //returns reg
		return colour;
	}
	public void setColour(String c)
	{   //returns reg
		colour = c;
	}

	/**
	 * Set warning to this vehicle
	 */
	public void setWarning()
	{
		warning++;
	}
	public void deleteWarning()//Removes 1 warning
	{
		warning--;
	}
	/**
	 * @return vehicle warning status
	 */
	public int getWarning()
	{
		return warning;
	}
	public boolean getSuspended() {
		return suspended;
	}
	public void setSuspended(boolean s) {
		suspended=s;
	}
	public int getAccesses() {
		return access;
	}
	public void addAccess() {//Adds 1 to the access count
		access++;
	}


}