  
/* Generated by Together */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package javaapplication37;

import java.util.Hashtable;
import java.util.Iterator;
import java.util.Set;


/**
 * Each instance of Vehicle_info models an actual physical vehicle, so no two instances
 * may have the same registration number. There is no direct notation for this. Instead
 * the Vehicle list object collecting the Vehicles must enforce it by checking new additions
 * - the use of a HashTable in Vehicle_list with the registration number as key is helpful
 * with this.
 *
 * This class must contain at least the registration number, and may have any other attributes
 * that the University may from time to time find useful (such as car make, model, colour...).
 * @author bruce
 */
public class Vehicle_info {
    /**
     * The vehicle's registration number.
     */
    private String regNo;
    private String make;
    private String model;
    private String colour;
    
    private String permitId;
    private int warning;
    private Permit permit;
    
    private Hashtable vehicles;
    private Hashtable permitted;
    
    
    public Vehicle_info(String regNo)
    {
        this.regNo = regNo;
    }
    
    public Vehicle_info(String regNo, String make, String model, String colour, String permitId)
    {
        this.regNo = regNo;
        this.make = make;
        this.model = model;
        this.colour = colour;
        this.permitId = permitId;
    }
    
    //Returns a hashtable where all of the vehicles link to the entered permitId
//    public Hashtable permittedVehicles(String regNo, int permitId)
//    {
//        Set<String> permits = vehicles.keySet();
//        Iterator<String> iterator = permits.iterator();
//        
//        while (iterator.hasNext()) 
//        {
//            String key = iterator.next();
//            Permit p = (Permit) vehicles.get(key);
//            if(vehicles.containsValue(p.getUID() == permitId))
//            {
//                permitted.put(regNo, permitId);
//            }
//        }
//        
//        return permitted;
//    }
    
    //Returns instance of Vehilce_info for the regNo entered today
    public Vehicle_info enteredToday(String regNo)
    {
        Vehicle_info today;
        today = (Vehicle_info) vehicles.get(regNo);
        return today;
    }

    /**
     * Each vehicle (and so each registration number) is associated with exactly one permit,
     * which describes its authorisation to enter the campus (or not!).
     *
     * This attribute references the permit associated with this vehicle. It allows the permit
     * status of any vehicle to be accessed via the Vehicle_list knowing only the registration
     * number - for example for barrier checks, recording warnings, and so on.
     *
     * Note that many vehicles may be associated with the same permit.
     * @supplierCardinality 1
     * @clientCardinality 1..*
     * @label Allowed entry by
     * @directed
    public Vehicle_info(String regNo){
        lnkPermit = new Permit();
        this.regNo = regNo;
        this.warning = false;
   }
     */
    public boolean hasPermit()
    {   
    	if (permit!=null) {
    		return true;
    	}else {
    		return false;
    	}
    }
    public Permit getPermit() {
        return permit;
    }
//    }
//    public getPermitDetails() {
//    	
//    }
    
    public void setPermit(Permit p)
    {   //Will need to add calls to permit class to access permit methods

    	permit = p;
  
    }
     /**
     * @return vehicle registration
     */
    public String getReg()
    {   //returns reg
        return regNo;
    }

     /**
     * Set warning to this vehicle
     */
    public void setWarning()
    {
        warning++;
    }
    public void deleteWarning()
    {
        warning--;
    }
     /**
     * @return vehicle warning status
     */
        public int getWarning()
        {
            return warning;
        }


}